config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "users#index"
  # Define endpoints for
  post "/api/register", to: 'authentication#register'
  post '/api/login', to: 'authentication#login'
  get '/api/users/:user_id/posts', to: 'posts#posts'
  get '/api/posts/:id/comments', to: 'comments#comments'
  post '/api/comments', to: 'comments#add_comment'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, length: 1..250, presence: true, allow_blank: false
  validates :comments_counter, numericality: { only_integer: true, greater_than: -1 }
  validates :likes_counter, numericality: { only_integer: true, greater_than: -1 }

  def update_posts_counter
    author.increment!(:posts_counter)
    author.save
  end

  def recent_comments
    comments.order('created_at DESC').includes(:author).limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_request

  def index
    @user = User.find(params[:user_id])
  end

  def show
    @user = User.where(id: params[:user_id])[0]
    @post = @user.posts.where(id: params[:id])[0]
    @posts = Post.where(author_id: params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.update_posts_counter

    respond_to do |format|
      if @post.save
        flash[:notice] = 'Post created succesfully'
        format.html { redirect_to "#{users_path}/#{current_user.id}" }
      else
        flash[:notice] = 'Failed creation a post. Try again'
        format.html { render :new }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @author = @post.author
    @author.posts_counter -= 1
    @post.destroy!
    redirect_to user_posts_path(id: @author.id), notice: 'Post was deleted successfully!'
  end

  def posts
    user = User.find(params[:user_id])

    respond_to do |format|
      format.json { render json: user.posts }
    end
  end

  private

  def post_params
    params.require(:post).permit(:author_id, :title, :text, :comments_counter, :likes_counter)
  end
end

app/views/posts/_add_comment.html.erb
<%= form_with model: Comment.new, url: request.url + "/create_comment" do |form| %>
  <%= form.hidden_field :author_id, value: current_user.id %>
  <%= form.hidden_field :post_id, value: @post.id %>
  <a href="<%= users_path + "/" + current_user.id.to_s %>"><%= current_user.name %></a>:
  <%= form.text_field :text %>
  <%= form.submit "Create Comment" %>
<% end %>   

app/views/posts/_like.html.erb
<%= form_with model: Like.new, url: url do |form| %>
  <%= form.hidden_field :author_id, value: current_user.id %>
  <%= form.hidden_field :post_id, value: post.id %>
  <%= form.submit "Like" %>
<% end %> 

app/views/posts/_new.html.erb
<%= form_with model: Post.new, url: "/posts/create", class: "new-post-form" do |form| %>
  <%= form.hidden_field :author_id, value: current_user.id %>
  <div class="field">
    <%= form.text_field :title, placeholder: "Title" %>
  </div>  
  <br>
  <%= form.text_area :text, placeholder: "Text" %>
  <br>
  <%= form.submit %>
<% end %>  

app/views/posts/index.html.erb
<section class="posts-section">
  <% if @user %>
    <div class="user-card">
      <img class="user-card-photo" src="<%= @user.photo %>"> 
      <div class="user-card-header bordered-box">
        <h2 class="user-card-username" ><%= @user.name %> </h2>
        <div class="user-card-postnumber">Number of Posts : <%= @user.posts.length %> </div>
      </div>
    </div>
    <ul class="mt-3">
      <%= render partial: "posts/new" %>
    <% @user.posts.each do |post| %>
      <li class="mb-1"> 
        <div class="bordered-box">
          <a href="<%= users_path + "/" + @user.id.to_s + "/posts/" + post.id.to_s %>" >
            <h2><%= post.title %></h2>
            <p><%= post.text %></p>
            
            <div class="post-info">Comments: <%= post.comments.length %>, Likes: <%= post.likes.length %></div>
          </a>
          <%= render partial: "posts/like", locals: { url: "/users/#{@user.id}/posts/#{post.id}/like", post: post } %>
        </div>
        <% if post.comments.length != 0 %>
          <div class="bordered-box">
            <% post.recent_comments.each do |comment| %>
              <div>
                <span><%= comment.author.name %> : </span>
                <span> <%= comment.text %> </span>
              </div>
            <% end %>
          </div>
        <% end %>
    <% end %>
       </li>
     
    </ul>
  <% else %>
    <h2> Not Found</h2>
  <% end %>
</section>  

app/views/posts/new.html.erb
<%= render partial: 'posts/new' %> 

app/views/posts/show.html.erb
<section class="posts-section">
  <% if @user %>
    <% if @post %>
      <div class="bordered-box">
        <div>
          <h2><%= @post.title %> by <%= @post.author.name %></h2>
          <div class="post-info">Comments: <%= @post.comments.length %>, Likes: <%= @post.likes.length %></div>
          <%= render partial: "posts/like", locals: { url: "/users/#{@user.id}/posts/#{@post.id}/like", post: @post } %>
           <% if can? :destroy, @post %>
    <%= button_to "Delete post 🗑", user_post_path(user_id: @post.author.id, post_id: @post.id), method: :delete, class: 'mb-10 hover:opacity-60'  %>
  <% end %>
        </div>
        <p>
        <%= @post.text %>
        </p>
      </div>
      <%= render partial: "posts/add_comment" %>
      <% if @post.comments.length != 0 %>
        <ul class="bordered-box">
          <% @post.recent_comments.each do |comment| %>
            <li>
            <span><%= comment.author.name %> : </span>
            <span> <%= comment.text %> </span>
            </li>
          <% end %>
        </ul>
      <% else %>
        <h2>No comments added </h2>
      <% end %>
      
    <% else %>
      <h2>Not founded</h2>
    <% end %>
  <% else %>
    <h1>Not founded</h1>
  <% end %>
</section>  